USE [master]
GO

/****** Object:  Database [zapper]    Script Date: 07/02/2012 00:00:05 ******/
CREATE DATABASE [zapper] ON  PRIMARY 
( NAME = N'zapper', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\zapper.mdf' , SIZE = 688128KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'zapper_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\zapper_log.LDF' , SIZE = 241216KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [zapper] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [zapper].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [zapper] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [zapper] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [zapper] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [zapper] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [zapper] SET ARITHABORT OFF 
GO

ALTER DATABASE [zapper] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [zapper] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [zapper] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [zapper] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [zapper] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [zapper] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [zapper] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [zapper] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [zapper] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [zapper] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [zapper] SET  DISABLE_BROKER 
GO

ALTER DATABASE [zapper] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [zapper] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [zapper] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [zapper] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [zapper] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [zapper] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [zapper] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [zapper] SET  READ_WRITE 
GO

ALTER DATABASE [zapper] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [zapper] SET  MULTI_USER 
GO

ALTER DATABASE [zapper] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [zapper] SET DB_CHAINING OFF 
GO


